# Generated by Django 5.1.3 on 2024-12-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team_role',
            field=models.CharField(blank=True, choices=[('Капитан', 'Капитан'), ('Участник', 'Участник')], max_length=64, null=True, verbose_name='Роль в команде'),
        ),
    ]
